---
apiVersion: codemowers.io/v1alpha1
kind: OIDCGWClient
metadata:
  name: authorization-code-sample-client
spec:
  redirectUris:
    - 'https://client-gab7y.codemowers.ee/cb'
  grantTypes:
    - 'authorization_code'
    - 'refresh_token' # might be supported by some implementations
  responseTypes:
    - 'code'
#    - 'code id_token' # might be needed in some implementations
#  tokenEndpointAuthMethod: 'client_secret_basic'
#  idTokenSignedResponseAlg: 'RS256'
