---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oidcgatewayusers.codemowers.io
spec:
  group: codemowers.io
  names:
    plural: oidcgatewayusers
    singular: oidcgatewayuser
    kind: OIDCGWUser
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          required:
            - spec
          type: object
          properties:
            spec:
              required:
                - profile
              type: object
              properties:
                acceptedTos:
                  type: boolean
                profile:
                  required:
                    - sub
                    - name
                    - company
                    - githubId
                  type: object
                  description: Profile
                  properties:
                    sub:
                      type: string
                    name:
                      type: string
                    company:
                      type: string
                    githubId:
                      type: integer
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oidcgatewayclients.codemowers.io
spec:
  group: codemowers.io
  names:
    plural: oidcgatewayclients
    singular: oidcgatewayclient
    kind: OIDCGWClient
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          required:
            - spec
          type: object
          properties:
            spec:
              required:
                - client_id
                - client_secret
                - grant_types
                - response_types
                - redirect_uris
              type: object
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
                grant_types:
                  type: array
                  items:
                    type: string
                response_types:
                  type: array
                  items:
                    type: string
                redirect_uris:
                  type: array
                  items:
                    type: string
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oidc-gateway
rules:
  - apiGroups:
      - codemowers.io
    resources:
      - oidcgatewayusers
      - oidcgatewayclients
    verbs:
      - get
      - list
      - watch
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oidc-gateway
subjects:
  - kind: ServiceAccount
    name: oidc-gateway
    namespace: veebkolm-gab7y

