---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oidcgatewayusers.codemowers.io
spec:
  group: codemowers.io
  names:
    plural: oidcgatewayusers
    singular: oidcgatewayuser
    kind: OIDCGWUser
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          required:
            - spec
          type: object
          properties:
            spec:
              required:
                - profile
              type: object
              properties:
                profile:
                  required:
                    - sub
                    - name
                    - company
                    - githubId
                  type: object
                  description: Profile
                  properties:
                    sub:
                      type: string
                    name:
                      type: string
                    company:
                      type: string
                    githubId:
                      type: integer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oidc-gateway
rules:
  - apiGroups:
      - codemowers.io
    resources:
      - oidcgatewayusers
    verbs:
      - get
      - list
      - watch
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oidc-gateway
subjects:
  - kind: ServiceAccount
    name: oidc-gateway
    namespace: veebkolm-gab7y

