---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oidcgatewayusers.codemowers.io
spec:
  group: codemowers.io
  names:
    plural: oidcgatewayusers
    singular: oidcgatewayuser
    kind: OIDCGWUser
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          required:
            - spec
          type: object
          properties:
            spec:
              required:
                - profile
                - groups
                - emails
              type: object
              properties:
                acceptedTos:
                  type: integer
                groups:
                  type: array
                  items:
                    type: string
                emails:
                  type: array
                  items:
                    type: string
                profile:
                  required:
                    - sub
                  type: object
                  description: Profile
                  properties:
                    sub:
                      type: string
                    name:
                      type: string
                    company:
                      type: string
                    githubId:
                      type: integer
      additionalPrinterColumns:
        - name: Name
          type: string
          jsonPath: .spec.profile.name
        - name: Emails
          type: string
          jsonPath: .spec.emails
        - name: Groups
          type: string
          jsonPath: .spec.groups
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oidcgatewayclients.codemowers.io
spec:
  group: codemowers.io
  names:
    plural: oidcgatewayclients
    singular: oidcgatewayclient
    kind: OIDCGWClient
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          required:
            - spec
          type: object
          properties:
            spec:
              type: object
              required:
                - redirectUris # TODO: add validation
                - grantTypes
                - responseTypes
              properties:
                redirectUris:
                  type: array
                  items:
                    type: string
                grantTypes:
                  type: array
                  items:
                    type: string
                    enum: [ 'implicit', 'authorization_code', 'refresh_token' ]
                responseTypes:
                  type: array
                  items:
                    type: string
                    enum: [ 'code id_token', 'code', 'id_token', 'none' ]
                tokenEndpointAuthMethod:
                  type: string
                  enum: [ 'client_secret_basic', 'client_secret_jwt', 'client_secret_post', 'private_key_jwt', 'none' ]
                idTokenSignedResponseAlg:
                  type: string
                  enum: [ 'PS256','RS256', 'ES256' ]
            status:
              type: object
              properties:
                gateway:
                  type: string
      additionalPrinterColumns:
        - name: Gateway
          type: string
          description: 'OIDC gateway deployment which manages this client'
          jsonPath: .status.gateway
        - name: Uris
          type: string
          description: 'Redirect URLs configured for this client'
          jsonPath: .redirectUris
