---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oidcgatewayusers.codemowers.io
spec:
  group: codemowers.io
  names:
    plural: oidcgatewayusers
    singular: oidcgatewayuser
    kind: OIDCGWUser
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          required:
            - spec
          type: object
          properties:
            spec:
              required:
                - profile
                - groups
                - emails
              type: object
              properties:
                acceptedTos:
                  type: integer
                groups:
                  type: array
                  items:
                    type: string
                emails:
                  type: array
                  items:
                    type: string
                profile:
                  required:
                    - sub
                  type: object
                  description: Profile
                  properties:
                    sub:
                      type: string
                    name:
                      type: string
                    company:
                      type: string
                    githubId:
                      type: integer
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oidcgatewayclients.codemowers.io
spec:
  group: codemowers.io
  names:
    plural: oidcgatewayclients
    singular: oidcgatewayclient
    kind: OIDCGWClient
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - redirectUris # TODO: add validation
          properties:
            redirectUris:
              type: array
              items:
                type: string
            status:
              type: object
              properties:
                gateway:
                  type: string
                hasSecret:
                  type: boolean
