---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oidc-gateway
  annotations:
    kubernetes.io/ingress.class: shared
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: traefik.codemowers.ee
spec:
  rules:
    - host: gateway-gab7y.codemowers.ee
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: oidc-gateway
                port:
                  number: 3000
  tls:
    - hosts:
        - "*.codemowers.ee"

---
apiVersion: v1
kind: Service
metadata:
  name: oidc-gateway
spec:
  type: ClusterIP
  selector:
    app: oidc-gateway
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: oidc-key-manager
spec:
  template:
    spec:
      serviceAccountName: oidc-gateway
      containers:
        - name: oidc-key-manager
          image: oidc-gateway
          command: [ '/app/node_modules/.bin/key-manager', 'initialize', '-c', 'cluster' ]
      restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-gateway
  labels:
    app: oidc-gateway
spec:
  selector:
    matchLabels:
      app: oidc-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: oidc-gateway
    spec:
      serviceAccountName: oidc-gateway
      containers:
        - name: oidc-gateway
          image: oidc-gateway
          ports:
            - containerPort: 3000
          env:
            - name: ISSUER_URL
              value: 'https://gateway-gab7y.codemowers.ee/'
            - name: DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: GH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-client
                  key: id
            - name: GH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-client
                  key: secret
            - name: GROUP_PREFIX
              value: 'codemowers'
            - name: ADMIN_GROUP
              value: 'codemowers:admins'
          envFrom:
            - secretRef:
                name: redis-oidc-gateway-owner-secrets
            - secretRef:
                  name: oidc-keys
            - secretRef:
                name: email-credentials
          readinessProbe:
            httpGet:
              path: /.well-known/openid-configuration
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 1
