---
apiVersion: codemowers.io/v1alpha1
kind: OIDCGWClient
metadata:
  name: implicit-id-token-sample-client
redirectUris:
  - 'https://client-gab7y.codemowers.ee/cb'
grantTypes:
  - 'implicit'
responseTypes:
  - 'id_token'
#tokenEndpointAuthMethod: 'client_secret_basic'
#idTokenSignedResponseAlg: 'RS256'
