---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oidc-gateway
rules:
  - apiGroups:
      - codemowers.io
    resources:
      - oidcgatewayusers
      - oidcgatewayusers/status
      - oidcgatewayclients
      - oidcgatewayclients/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oidc-gateway
subjects:
  - kind: ServiceAccount
    name: oidc-gateway
    namespace: veebkolm-gab7y
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-gateway
