---
apiVersion: codemowers.io/v1alpha1
kind: OIDCGWClient
metadata:
  name: test-client
spec:
  client_id: 'foo'
  client_secret: 'bar'
  grant_types: [ 'implicit', 'refresh_token', 'authorization_code' ]
  response_types: [ 'id_token' ]
  redirect_uris: [ 'https://client-gab7y.codemowers.ee/cb' ]
